### ISSUE TITLE
Code competion doesn't work on osx serra.

### ISSUE THREAD

**Issue by AurevoirXavier** [martrik/Haskelly#5]
I already installed intero, but it doesn't work.

**Comment by martrik** [comment]
@AurevoirXavier could you tell us what OS are you using? Also, are you working on a Stack project?

**Comment by AurevoirXavier** [comment]
@martrik I just create a xx.hs on my desktop.

**Comment by martrik** [comment]
Can you try running these commands in the terminal and tell us if you get any error?

1. Cd to Desktop: `cd ~/Desktop`
2. Create new .hs file: `touch test.hs`
3. Load Stack with Intero: `stack ghci --with-ghc intero`
4. Load the file into GHCi: `:l test.hs`
5. Request completions with intero: `:complete-at /Users/{username}/Desktop/test.hs 0 0 0 0`

If running 5 provides you with a list of completions like the one attached, Haskelly should be working fine.

<img width="608" alt="screen shot 2017-01-15 at 13 58 48" src="https://cloud.githubusercontent.com/assets/1800680/21963044/d6aeca12-db2a-11e6-9d15-f496449f8ee3.png">

**Comment by AurevoirXavier** [comment]
@martrik 

![image](https://cloud.githubusercontent.com/assets/16152305/21964591/b73a7910-db89-11e6-8fd7-910954bb35c8.png)

still can't work.

**Comment by AurevoirXavier** [comment]
![image](https://cloud.githubusercontent.com/assets/16152305/21964674/71d20bc0-db8b-11e6-9286-a603306e1cf0.png)

**Comment by martrik** [comment]
OK I know what's causing the bug. You have Prelude configured to show λ> instead of Main*>. This was actually a known bug which was closed since we thought it had been fixed. Give us one hour and we'll release an update which fixes the issue.

**Comment by AurevoirXavier** [comment]
@martrik when I work on archlinux, I use the same configuration. It can work correctly.

**Comment by martrik** [comment]
Let us know if the version 0.2.6 solves the issue :)

**Comment by AurevoirXavier** [comment]
![image](https://cloud.githubusercontent.com/assets/16152305/21964897/87e9185a-db8f-11e6-8e67-098943471102.png)

I can't update it.

**Comment by martrik** [comment]
Have you tried uninstalling and installing it again? If that doesn't work maybe you'll have to do the same for VS Code.

**Comment by AurevoirXavier** [comment]
It(version 0.2.7) works after I restart my computer. Your help was greatly appreciated.

**Comment by AurevoirXavier** [comment]
By the way, many i think many people use 'Haskelly' and 'Haskell Syntax Highlighting'  at the same time. In this case, I suggest you to add a configuration the user can turn on or turn off auto completing for some function keyword likes 'foldr' 'map'...

**Comment by martrik** [comment]
You mean because of the snippets right? Do you think that I'd be nice to have them also in Haskelly? Either way, I think it makes sense to add a configuration to disable the code suggestions for the ones that snippets are provided. Thanks for the idea!

**Comment by AurevoirXavier** [comment]
You‘d better not to add it in 'Haskelly' completely, because some people(those who don't like 'Haskell Syntax Highlighting') don't like 'snippets'. If you add it, setting up a configuration that would be a good idea. So I can uninstall 'Haskell Syntax Highlighting', and those people can turn 'snippets' off.  : D

**Comment by martrik** [comment]
Thanks for the insight! We will add snippets in the next release (0.3.0) and they will be configurable :)

**Comment by AurevoirXavier** [comment]
Looking forward your good news. 👍
